name: Blossom
author: RavvenLord
main: com.ravvenlord.blossom.Blossom
version: 1.0.0
api-version: "1.14"
commands:
  setname:
    description: 'Sets the player name to the provided arguments'
    permission: 'blossom.set'
